DROP TABLE IF EXISTS EMPLOYE CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS TELETRAVAIL CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS CONGES CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS ABSENCE CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS HEURESUPP CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS NOTIFICATION CASCADE CONSTRAINTS;
DROP TABLE IF EXISTS HORAIRE CASCADE CONSTRAINTS;

CREATE TABLE EMPLOYE
  (
    id_emp INT NOT NULL AUTO_INCREMENT,
    nom VARCHAR(20) NOT NULL,
    prenom VARCHAR(20) NOT NULL,
    date_naissance DATE NOT NULL,
    adresse VARCHAR(50) NOT NULL,
    telephone VARCHAR(10) NOT NULL,
    mail VARCHAR(50) NOT NULL,
    mdp VARCHAR(20) NOT NULL,
    poste VARCHAR(20) NOT NULL,
    tt_possible BOOLEAN NOT NULL,
    est_responsable BOOLEAN NOT NULL,
    PRIMARY KEY (id_emp)
  );

CREATE TABLE TELETRAVAIL
  (
    id_tt INT NOT NULL AUTO_INCREMENT,
    id_employe INT NOT NULL,
    id_responsable_validant INT NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    est_valide BOOLEAN NOT NULL,
    PRIMARY KEY (id_tt),
    FOREIGN KEY (id_employe) REFERENCES EMPLOYE(id_emp),
    FOREIGN KEY (id_responsable_validant) REFERENCES EMPLOYE(id_emp) ON DELETE CASCADE
  );

CREATE TABLE CONGES
  (
    id_conges INT NOT NULL AUTO_INCREMENT,
    id_employe INT NOT NULL,
    id_responsable_validant INT NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    est_valide BOOLEAN NOT NULL,
    PRIMARY KEY (id_conges),
    FOREIGN KEY (id_employe) REFERENCES EMPLOYE(id_emp),
    FOREIGN KEY (id_responsable_validant) REFERENCES EMPLOYE(id_emp) ON DELETE CASCADE
  );

CREATE TABLE ABSENCE
  (
    id_abs INT NOT NULL AUTO_INCREMENT,
    id_employe INT NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    PRIMARY KEY (id_abs),
    FOREIGN KEY (id_employe) REFERENCES EMPLOYE(id_emp) ON DELETE CASCADE
  );

CREATE TABLE HEURESUPP
  (
    id_hsupp INT NOT NULL AUTO_INCREMENT,
    id_employe INT NOT NULL,
    date DATE NOT NULL,
    numero_semaine INT NOT NULL,
    heure_debut TIME NOT NULL,
    heure_fin TIME NOT NULL,
    PRIMARY KEY (id_hsupp),
    FOREIGN KEY (id_employe) REFERENCES EMPLOYE(id_emp) ON DELETE CASCADE
  );

CREATE TABLE NOTIFICATION
  (
    id_notif INT NOT NULL AUTO_INCREMENT,
    id_employe INT NOT NULL,
    date DATE NOT NULL,
    message VARCHAR(100) NOT NULL,
    est_lue BOOLEAN NOT NULL,
    PRIMARY KEY (id_notif),
    FOREIGN KEY (id_employe) REFERENCES EMPLOYE(id_emp) ON DELETE CASCADE
  );

CREATE TABLE HORAIRE
  (
    id_horaire INT NOT NULL AUTO_INCREMENT,
    id_employe INT NOT NULL,
    date DATE NOT NULL,
    numero_semaine INT NOT NULL,
    heure_debut TIME NOT NULL,
    heure_fin TIME NOT NULL,
    PRIMARY KEY (id_horaire),
    FOREIGN KEY (id_employe) REFERENCES EMPLOYE(id_emp) ON DELETE CASCADE
  );