DROP TABLE IF EXISTS EMPLOYE;
DROP TABLE IF EXISTS TELETRAVAIL;
DROP TABLE IF EXISTS CONGES;
DROP TABLE IF EXISTS ABSENCE;
DROP TABLE IF EXISTS HEURESUPP;
DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS HORAIRE;

CREATE TABLE EMPLOYE
(
    id_emp INT NOT NULL AUTO_INCREMENT,
    nom VARCHAR(20) NOT NULL,
    prenom VARCHAR(20) NOT NULL,
    date_naissance DATE NOT NULL,
    adresse VARCHAR(50) NOT NULL,
    telephone VARCHAR(10) NOT NULL,
    mail VARCHAR(50) NOT NULL,
    mdp VARCHAR(20) NOT NULL,
    poste VARCHAR(20) NOT NULL,
    tt_possible BOOLEAN NOT NULL,
    est_responsable BOOLEAN NOT NULL,
    PRIMARY KEY (id_emp)
);

CREATE TABLE TELETRAVAIL
(
    id_tt INT NOT NULL AUTO_INCREMENT,
    id_employe INT NOT NULL,
    id_responsable_validant INT NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    est_valide BOOLEAN NOT NULL,
    PRIMARY KEY (id_tt),
    FOREIGN KEY (id_employe) REFERENCES EMPLOYE(id_emp),
    FOREIGN KEY (id_responsable_validant) REFERENCES EMPLOYE(id_emp)
);