DROP TABLE IF EXISTS `Employe`;
DROP TABLE IF EXISTS `Teletravail`;
DROP TABLE IF EXISTS `Conges`;
DROP TABLE IF EXISTS `Absence`;
DROP TABLE IF EXISTS `HeureSupp`;
DROP TABLE IF EXISTS `Notification`;
DROP TABLE IF EXISTS `Horaire`;

